baseurl = "https://agitated-franklin-4873ae.netlify.com/"
theme = "hugo-geo @ b91ad6f"
themesdir = "themes"
relativeURLs = false
languageCode = "en-uk"
title = "WhoIsHou"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "houman@whoishou.com"

	profilepic = "img/profile.jpg"
	
	title = "whoishou"
#	subtitle = "Houman"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/whoishou"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/whoishou"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://www.linkedin.com/in/houmanmohammadiyan/"

	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
#	[[params.navlinks]]
#	name = "Tutorials"
#	url = "tutorial/"

    [[params.navlinks]]
	name = "Homelab"
	url = "homelab/"
